### ISSUE TITLE
Code consolidation

### ISSUE THREAD

**Issue by shisha101** [shisha101/ROSRagnarEDU#8]
Currently there is a lot of code distributed on different forks of Blueworkforce concerning ROSRagnarEDU, It would be useful to consolidate all the code back into Blueworkforce and test if it will not break the current implementation.

I will have a look at the following forks: 
[akgoins](https://github.com/akgoins/ROSRagnarEDU) smooth_lines
[Jmeyer1292](https://github.com/Jmeyer1292/ROSRagnarEDU) kinematics_tools

@ipa-mirb , @Jmeyer1292 , @akgoins

**Comment by shisha101** [comment]
the branch concerning the signature demo and trajectory smoothing, turned out to be purely a demo, and the trajectory smoothing being done there cannot be reused in my opinion. It might not be worth integrating it completely into **master** since we would introduce OpenCV as a dependency.

please let us know if we have overlooked something.

**Comment by shisha101** [comment]
the branch kinematics_tools available [here](https://github.com/Jmeyer1292/ROSRagnarEDU) implements some useful helper functions and wrappers that would be useful to incorporate into the current code base.

**Comment by akgoins** [comment]
@shisha101, yes, the signature demo and smooth lines branches were only for creating a working demo to run on the Ragnar.  I plan to eventually break this out into a separate, standalone library so that it can be used elsewhere.  It might be helpful to put some of these issues on the main Blueworkforce repo rather than on your fork so that everyone can see the conversation better.
